spring:
  freemarker:
    suffix: .ftl
  datasource:
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      showSql: true
      formatSql: true
